- name: Manage the lifecycle of Foreman on OpenShift™
  hosts: localhost
  gather_facts: no
  connection: local
  vars:
    minishift: true
    cluster_up: false
    pulp_worker_count: 2
    registry: quay.io/foreman
    foreman_providers: false
  pre_tasks:
    - set_fact:
        deployment_state: present
      tags:
        - restart
        - start
        - stop
    - set_fact:
        deployment_state: absent
      tags:
        - destroy

    - set_fact:
        project_name: "{{ project_name | default('foreman') }}"
      tags:
        - always

    - set_fact:
        application_hostname: "{{ application_hostname | default('') }}"
      tags:
        - always
    - shell: minishift ip
      register: minishift_ip
      when: minishift == true
      tags:
        - always
    - set_fact:
        application_hostname: "foreman.{{ minishift_ip.stdout }}.nip.io"
      when: application_hostname == '' and minishift == true and cluster_up == false
      tags:
        - always
    - set_fact:
        application_hostname: "foreman.{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}.nip.io"
      when: application_hostname == '' and cluster_up == true and minishift == false
      tags:
        - always
  roles:
    - project
    - service-accounts
    - foreman
    - foreman-proxy
