---
- name: Create Candlepin deployment
  openshift_raw:
    state: "{{ deployment_state }}"
    force: false
    definition:
      apiVersion: v1
      kind: DeploymentConfig
      metadata:
        name: candlepin
        namespace: "{{ project_name }}"
        labels:
          app: "{{ project_name }}"
          service: candlepin
      spec:
        replicas: 1
        strategy:
          type: Rolling
          rollingParams:
            timeoutSeconds: 900
        template:
          metadata:
            labels:
              app: "{{ project_name }}"
              service: candlepin
          spec:
            serviceAccount: anyuid
            serviceAccountName: anyuid
            containers:
              - name: candlepin
                state: present
                securityContext: {}
                volumeMounts:
                  - readOnly: true
                    mountPath: /etc/candlepin/certs
                    name: ca
                env:
                  - name: POSTGRES_DB
                    value: foreman
                  - name: POSTGRES_USER
                    value: foreman
                  - name: POSTGRES_PASSWORD
                    value: foreman
                  - name: POSTGRES_PORT
                    value: '5432'
                  - name: POSTGRES_SERVICE
                    value: postgres
                  - name: QPID_SERVICE
                    value: qpid
                  - name: QPID_PORT
                    value: '5672'
                image: "{{ registry }}/candlepin:latest"
            volumes:
              - name: ca
                secret:
                  secretName: ca
                  items:
                    - path: candlepin-ca.key
                      key: ca.key
                    - path: candlepin-ca.crt
                      key: ca.crt
  tags:
    - start
