---
- name: Create service
  k8s_raw:
    state: "{{ deployment_state }}"
    force: false
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: candlepin
        namespace: "{{ project_name }}"
        labels:
          app: "{{ project_name }}"
          service: candlepin
      spec:
        selector:
          app: "{{ project_name }}"
          service: candlepin
        ports:
          - protocol: TCP
            targetPort: 8080
            name: port-8080-tcp
            port: 8080
  tags:
    - start
